name: ci-bonsai-linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Get current version
        id: version
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
      - name: Compile
        run: |
          cd src/bonsai && make dist PLATFORM=linux PYVERSION=py311 IS_STABLE=TRUE
      - name: Find zip file name
        id: find_zip
        run: |
          filepath=$(ls src/bonsai/dist/bonsai_*.zip)
          echo "filepath=$filepath" >> $GITHUB_OUTPUT
          echo "filename=$(basename $filepath)" >> $GITHUB_OUTPUT
      - name: Upload zip file to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.find_zip.outputs.filepath }}
          asset_name: ${{ steps.find_zip.outputs.filename }}
          release_name: "bonsai-${{steps.version.outputs.version}}"
          tag: "bonsai-${{steps.version.outputs.version}}"
          overwrite: true
